### ISSUE TITLE
Sealed Secret in Kubernetes

### ISSUE THREAD

**Issue by drnow4u** [OWASP/wrongsecrets#858]
In the repository would be committed file containing [Sealed Secret](https://github.com/bitnami-labs/sealed-secrets)  e.g.:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
```
Sealed Secret is  asymmetrically encrypted and only the Sealed Secret Controller deployed in Kubernetes can decrypt it. Such decrypted secrets "unsealed" are stored as classic Kubernetes secret.

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: mynamespace
data:
  foo: YmFy  # <- base64 encoded "bar"
```

@commjoen could you describe proposed on Slack attack vector?
